repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: mixed-line-ending
      - id: check-merge-conflict
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.5.0
    hooks:
      - id: reorder-python-imports
        args: [ --py38-plus ]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.15.0
    hooks:
      - id: pyupgrade
        args: [ --py38-plus ]
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        args: [
            --no_implicit_optional,
            --disallow_untyped_defs,
            --disallow_incomplete_defs,
            --disallow_any_generics,
            --check_untyped_defs,
        ]
  - repo: https://github.com/psf/black
    rev: 21.4b0
    hooks:
      - id: black
        args: [ --line-length=120 ]
ci:
    autofix_prs: true
    autoupdate_schedule: weekly
    skip: []
    submodules: false
